all:
	pdflatex crowdsourcing
	- bibtex crowdsourcing && pdflatex crowdsourcing && pdflatex crowdsourcing

clean:
	(rm -rf *.ps *.log *.dvi *.aux *.*% *.lof *.lop *.lot *.toc *.idx *.ilg *.ind *.bbl *blg)
